### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by DamianGodDe** [jgord559/Tiktok-AutoClaimer#7]
when i run the program after the session id this problem says to me
Traceback (most recent call last):
  File "E:\TT\TikTok-AutoClaimer-main\Tiktok-AutoClaimer-main\tiktok_claimer.py", line 64, in <module>
    tttoken = (tttokenreq.cookies['Here was my tt.token'])
  File "C:\Users\!\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "C:\Users\1\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='Here was this token thing', domain=None, path=None"

E:\TT\TikTok-AutoClaimer-main\Tiktok-AutoClaimer-main>

**Comment by jgord559** [comment]
looks like your rate limited

**Comment by DamianGodDe** [comment]
> looks like your rate limited

what does it mean ?
